server:
  port: 8080

spring:

  application:
    name: demo


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


  datasource:
    url: jdbc:mysql://localhost:3306/rabbit_db
    username: root
    password: springboot


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect




